# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: iclab/abc/enum.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='iclab/abc/enum.proto',
  package='iclab.abc.enum',
  syntax='proto3',
  serialized_options=_b('\n\026kaist.iclab.abc.protosB\nEnumProtos'),
  serialized_pb=_b('\n\x14iclab/abc/enum.proto\x12\x0eiclab.abc.enum*D\n\nGenderType\x12\x12\n\x0eGENDER_UNKNOWN\x10\x00\x12\x0f\n\x0bGENDER_MALE\x10\x01\x12\x11\n\rGENDER_FEMALE\x10\x02*\x94\x03\n\x0bRawDataType\x12\x07\n\x03\x41LL\x10\x00\x12\x13\n\x0f\x41PP_USAGE_EVENT\x10\x01\x12\x12\n\x0e\x41PP_USAGE_STAT\x10\x02\x12\x0b\n\x07\x42\x41TTERY\x10\x03\x12\x0c\n\x08\x43\x41LL_LOG\x10\x04\x12\x10\n\x0c\x43ONNECTIVITY\x10\x05\x12\x10\n\x0c\x44\x41TA_TRAFFIC\x10\x06\x12\x10\n\x0c\x44\x45VICE_EVENT\x10\x07\x12\x0c\n\x08LOCATION\x10\x08\x12\t\n\x05MEDIA\x10\t\x12\x0b\n\x07MESSAGE\x10\n\x12\x10\n\x0cNOTIFICATION\x10\x0b\x12\x1b\n\x17PHYSICAL_ACTIVITY_EVENT\x10\x0c\x12\x08\n\x04WIFI\x10\r\x12\x13\n\x0fPHYSICAL_STATUS\x10\x0e\x12\x0e\n\nRAW_SENSOR\x10\x0f\x12\x0b\n\x07WEATHER\x10\x10\x12\x14\n\x10\x45MOTIONAL_STATUS\x10\x11\x12\x15\n\x11\x45XPERIENCE_SAMPLE\x10\x12\x12\x0f\n\x0b\x42INARY_FILE\x10\x13\x12\x11\n\rINSTALLED_APP\x10\x14\x12 \n\x1cPHYSICAL_ACTIVITY_TRANSITION\x10\x15*k\n\x0e\x44\x61taSourceType\x12\x0b\n\x07UNKNOWN\x10\x00\x12\t\n\x05PHONE\x10\x01\x12\x0e\n\nWRIST_WORN\x10\x02\x12\n\n\x06TABLET\x10\x03\x12\x0c\n\x08\x43OMPUTER\x10\x04\x12\x0e\n\nIOT_SENSOR\x10\x05\x12\x07\n\x03WEB\x10\x06\x42$\n\x16kaist.iclab.abc.protosB\nEnumProtosb\x06proto3')
)

_GENDERTYPE = _descriptor.EnumDescriptor(
  name='GenderType',
  full_name='iclab.abc.enum.GenderType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='GENDER_UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GENDER_MALE', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GENDER_FEMALE', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=40,
  serialized_end=108,
)
_sym_db.RegisterEnumDescriptor(_GENDERTYPE)

GenderType = enum_type_wrapper.EnumTypeWrapper(_GENDERTYPE)
_RAWDATATYPE = _descriptor.EnumDescriptor(
  name='RawDataType',
  full_name='iclab.abc.enum.RawDataType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ALL', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='APP_USAGE_EVENT', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='APP_USAGE_STAT', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BATTERY', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CALL_LOG', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CONNECTIVITY', index=5, number=5,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DATA_TRAFFIC', index=6, number=6,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DEVICE_EVENT', index=7, number=7,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LOCATION', index=8, number=8,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MEDIA', index=9, number=9,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MESSAGE', index=10, number=10,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='NOTIFICATION', index=11, number=11,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PHYSICAL_ACTIVITY_EVENT', index=12, number=12,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WIFI', index=13, number=13,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PHYSICAL_STATUS', index=14, number=14,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RAW_SENSOR', index=15, number=15,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WEATHER', index=16, number=16,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='EMOTIONAL_STATUS', index=17, number=17,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='EXPERIENCE_SAMPLE', index=18, number=18,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BINARY_FILE', index=19, number=19,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INSTALLED_APP', index=20, number=20,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PHYSICAL_ACTIVITY_TRANSITION', index=21, number=21,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=111,
  serialized_end=515,
)
_sym_db.RegisterEnumDescriptor(_RAWDATATYPE)

RawDataType = enum_type_wrapper.EnumTypeWrapper(_RAWDATATYPE)
_DATASOURCETYPE = _descriptor.EnumDescriptor(
  name='DataSourceType',
  full_name='iclab.abc.enum.DataSourceType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PHONE', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WRIST_WORN', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TABLET', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='COMPUTER', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='IOT_SENSOR', index=5, number=5,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WEB', index=6, number=6,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=517,
  serialized_end=624,
)
_sym_db.RegisterEnumDescriptor(_DATASOURCETYPE)

DataSourceType = enum_type_wrapper.EnumTypeWrapper(_DATASOURCETYPE)
GENDER_UNKNOWN = 0
GENDER_MALE = 1
GENDER_FEMALE = 2
ALL = 0
APP_USAGE_EVENT = 1
APP_USAGE_STAT = 2
BATTERY = 3
CALL_LOG = 4
CONNECTIVITY = 5
DATA_TRAFFIC = 6
DEVICE_EVENT = 7
LOCATION = 8
MEDIA = 9
MESSAGE = 10
NOTIFICATION = 11
PHYSICAL_ACTIVITY_EVENT = 12
WIFI = 13
PHYSICAL_STATUS = 14
RAW_SENSOR = 15
WEATHER = 16
EMOTIONAL_STATUS = 17
EXPERIENCE_SAMPLE = 18
BINARY_FILE = 19
INSTALLED_APP = 20
PHYSICAL_ACTIVITY_TRANSITION = 21
UNKNOWN = 0
PHONE = 1
WRIST_WORN = 2
TABLET = 3
COMPUTER = 4
IOT_SENSOR = 5
WEB = 6


DESCRIPTOR.enum_types_by_name['GenderType'] = _GENDERTYPE
DESCRIPTOR.enum_types_by_name['RawDataType'] = _RAWDATATYPE
DESCRIPTOR.enum_types_by_name['DataSourceType'] = _DATASOURCETYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
