# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import tossChatData_pb2 as tossChatData__pb2


class tossChatStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.tossChatData = channel.unary_unary(
        '/tossChat/tossChatData',
        request_serializer=tossChatData__pb2.ChatData.SerializeToString,
        response_deserializer=tossChatData__pb2.returnData.FromString,
        )


class tossChatServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def tossChatData(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_tossChatServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'tossChatData': grpc.unary_unary_rpc_method_handler(
          servicer.tossChatData,
          request_deserializer=tossChatData__pb2.ChatData.FromString,
          response_serializer=tossChatData__pb2.returnData.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'tossChat', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
