# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from iclab.abc import common_pb2 as iclab_dot_abc_dot_common__pb2
from iclab.abc.mesh_up import calendar_pb2 as iclab_dot_abc_dot_mesh__up_dot_calendar__pb2


class GoogleCalendarServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.ListGoogleCalendar = channel.unary_stream(
        '/iclab.abc.external.calendar.GoogleCalendarService/ListGoogleCalendar',
        request_serializer=iclab_dot_abc_dot_mesh__up_dot_calendar__pb2.GoogleCalendarListQuery.SerializeToString,
        response_deserializer=iclab_dot_abc_dot_mesh__up_dot_calendar__pb2.GoogleCalendar.FromString,
        )
    self.GetGoogleCalendar = channel.unary_unary(
        '/iclab.abc.external.calendar.GoogleCalendarService/GetGoogleCalendar',
        request_serializer=iclab_dot_abc_dot_mesh__up_dot_calendar__pb2.GoogleCalendarSingleQuery.SerializeToString,
        response_deserializer=iclab_dot_abc_dot_mesh__up_dot_calendar__pb2.GoogleCalendar.FromString,
        )
    self.CreateGoogleCalendar = channel.unary_unary(
        '/iclab.abc.external.calendar.GoogleCalendarService/CreateGoogleCalendar',
        request_serializer=iclab_dot_abc_dot_mesh__up_dot_calendar__pb2.GoogleCalendarPostQuery.SerializeToString,
        response_deserializer=iclab_dot_abc_dot_mesh__up_dot_calendar__pb2.GoogleCalendar.FromString,
        )
    self.UpdateGoogleCalendar = channel.unary_unary(
        '/iclab.abc.external.calendar.GoogleCalendarService/UpdateGoogleCalendar',
        request_serializer=iclab_dot_abc_dot_mesh__up_dot_calendar__pb2.GoogleCalendarPostQuery.SerializeToString,
        response_deserializer=iclab_dot_abc_dot_mesh__up_dot_calendar__pb2.GoogleCalendar.FromString,
        )
    self.DeleteGoogleCalendar = channel.unary_unary(
        '/iclab.abc.external.calendar.GoogleCalendarService/DeleteGoogleCalendar',
        request_serializer=iclab_dot_abc_dot_mesh__up_dot_calendar__pb2.GoogleCalendarSingleQuery.SerializeToString,
        response_deserializer=iclab_dot_abc_dot_common__pb2.Empty.FromString,
        )
    self.ListGoogleCalendarEvent = channel.unary_stream(
        '/iclab.abc.external.calendar.GoogleCalendarService/ListGoogleCalendarEvent',
        request_serializer=iclab_dot_abc_dot_mesh__up_dot_calendar__pb2.GoogleCalendarEventListQuery.SerializeToString,
        response_deserializer=iclab_dot_abc_dot_mesh__up_dot_calendar__pb2.GoogleCalendarEvent.FromString,
        )
    self.GetGoogleCalendarEvent = channel.unary_unary(
        '/iclab.abc.external.calendar.GoogleCalendarService/GetGoogleCalendarEvent',
        request_serializer=iclab_dot_abc_dot_mesh__up_dot_calendar__pb2.GoogleCalendarEventSingleQuery.SerializeToString,
        response_deserializer=iclab_dot_abc_dot_mesh__up_dot_calendar__pb2.GoogleCalendarEvent.FromString,
        )
    self.CreateGoogleCalendarEvent = channel.unary_unary(
        '/iclab.abc.external.calendar.GoogleCalendarService/CreateGoogleCalendarEvent',
        request_serializer=iclab_dot_abc_dot_mesh__up_dot_calendar__pb2.GoogleCalendarEventPostQuery.SerializeToString,
        response_deserializer=iclab_dot_abc_dot_mesh__up_dot_calendar__pb2.GoogleCalendarEvent.FromString,
        )
    self.UpdateGoogleCalendarEvent = channel.unary_unary(
        '/iclab.abc.external.calendar.GoogleCalendarService/UpdateGoogleCalendarEvent',
        request_serializer=iclab_dot_abc_dot_mesh__up_dot_calendar__pb2.GoogleCalendarEventPostQuery.SerializeToString,
        response_deserializer=iclab_dot_abc_dot_mesh__up_dot_calendar__pb2.GoogleCalendarEvent.FromString,
        )
    self.DeleteGoogleCalendarEvent = channel.unary_unary(
        '/iclab.abc.external.calendar.GoogleCalendarService/DeleteGoogleCalendarEvent',
        request_serializer=iclab_dot_abc_dot_mesh__up_dot_calendar__pb2.GoogleCalendarEventSingleQuery.SerializeToString,
        response_deserializer=iclab_dot_abc_dot_common__pb2.Empty.FromString,
        )


class GoogleCalendarServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def ListGoogleCalendar(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetGoogleCalendar(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CreateGoogleCalendar(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UpdateGoogleCalendar(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DeleteGoogleCalendar(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ListGoogleCalendarEvent(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetGoogleCalendarEvent(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CreateGoogleCalendarEvent(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UpdateGoogleCalendarEvent(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DeleteGoogleCalendarEvent(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_GoogleCalendarServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'ListGoogleCalendar': grpc.unary_stream_rpc_method_handler(
          servicer.ListGoogleCalendar,
          request_deserializer=iclab_dot_abc_dot_mesh__up_dot_calendar__pb2.GoogleCalendarListQuery.FromString,
          response_serializer=iclab_dot_abc_dot_mesh__up_dot_calendar__pb2.GoogleCalendar.SerializeToString,
      ),
      'GetGoogleCalendar': grpc.unary_unary_rpc_method_handler(
          servicer.GetGoogleCalendar,
          request_deserializer=iclab_dot_abc_dot_mesh__up_dot_calendar__pb2.GoogleCalendarSingleQuery.FromString,
          response_serializer=iclab_dot_abc_dot_mesh__up_dot_calendar__pb2.GoogleCalendar.SerializeToString,
      ),
      'CreateGoogleCalendar': grpc.unary_unary_rpc_method_handler(
          servicer.CreateGoogleCalendar,
          request_deserializer=iclab_dot_abc_dot_mesh__up_dot_calendar__pb2.GoogleCalendarPostQuery.FromString,
          response_serializer=iclab_dot_abc_dot_mesh__up_dot_calendar__pb2.GoogleCalendar.SerializeToString,
      ),
      'UpdateGoogleCalendar': grpc.unary_unary_rpc_method_handler(
          servicer.UpdateGoogleCalendar,
          request_deserializer=iclab_dot_abc_dot_mesh__up_dot_calendar__pb2.GoogleCalendarPostQuery.FromString,
          response_serializer=iclab_dot_abc_dot_mesh__up_dot_calendar__pb2.GoogleCalendar.SerializeToString,
      ),
      'DeleteGoogleCalendar': grpc.unary_unary_rpc_method_handler(
          servicer.DeleteGoogleCalendar,
          request_deserializer=iclab_dot_abc_dot_mesh__up_dot_calendar__pb2.GoogleCalendarSingleQuery.FromString,
          response_serializer=iclab_dot_abc_dot_common__pb2.Empty.SerializeToString,
      ),
      'ListGoogleCalendarEvent': grpc.unary_stream_rpc_method_handler(
          servicer.ListGoogleCalendarEvent,
          request_deserializer=iclab_dot_abc_dot_mesh__up_dot_calendar__pb2.GoogleCalendarEventListQuery.FromString,
          response_serializer=iclab_dot_abc_dot_mesh__up_dot_calendar__pb2.GoogleCalendarEvent.SerializeToString,
      ),
      'GetGoogleCalendarEvent': grpc.unary_unary_rpc_method_handler(
          servicer.GetGoogleCalendarEvent,
          request_deserializer=iclab_dot_abc_dot_mesh__up_dot_calendar__pb2.GoogleCalendarEventSingleQuery.FromString,
          response_serializer=iclab_dot_abc_dot_mesh__up_dot_calendar__pb2.GoogleCalendarEvent.SerializeToString,
      ),
      'CreateGoogleCalendarEvent': grpc.unary_unary_rpc_method_handler(
          servicer.CreateGoogleCalendarEvent,
          request_deserializer=iclab_dot_abc_dot_mesh__up_dot_calendar__pb2.GoogleCalendarEventPostQuery.FromString,
          response_serializer=iclab_dot_abc_dot_mesh__up_dot_calendar__pb2.GoogleCalendarEvent.SerializeToString,
      ),
      'UpdateGoogleCalendarEvent': grpc.unary_unary_rpc_method_handler(
          servicer.UpdateGoogleCalendarEvent,
          request_deserializer=iclab_dot_abc_dot_mesh__up_dot_calendar__pb2.GoogleCalendarEventPostQuery.FromString,
          response_serializer=iclab_dot_abc_dot_mesh__up_dot_calendar__pb2.GoogleCalendarEvent.SerializeToString,
      ),
      'DeleteGoogleCalendarEvent': grpc.unary_unary_rpc_method_handler(
          servicer.DeleteGoogleCalendarEvent,
          request_deserializer=iclab_dot_abc_dot_mesh__up_dot_calendar__pb2.GoogleCalendarEventSingleQuery.FromString,
          response_serializer=iclab_dot_abc_dot_common__pb2.Empty.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'iclab.abc.external.calendar.GoogleCalendarService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
