# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: conversation.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='conversation.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x12\x63onversation.proto\"@\n\x08\x43hatData\x12\x12\n\nteam_index\x18\x01 \x01(\x05\x12\x12\n\nroom_index\x18\x02 \x01(\x05\x12\x0c\n\x04\x63hat\x18\x03 \x01(\t22\n\x0c\x43onversation\x12\"\n\x08makeChat\x12\t.ChatData\x1a\t.ChatData\"\x00\x62\x06proto3')
)




_CHATDATA = _descriptor.Descriptor(
  name='ChatData',
  full_name='ChatData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='team_index', full_name='ChatData.team_index', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='room_index', full_name='ChatData.room_index', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='chat', full_name='ChatData.chat', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=86,
)

DESCRIPTOR.message_types_by_name['ChatData'] = _CHATDATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ChatData = _reflection.GeneratedProtocolMessageType('ChatData', (_message.Message,), dict(
  DESCRIPTOR = _CHATDATA,
  __module__ = 'conversation_pb2'
  # @@protoc_insertion_point(class_scope:ChatData)
  ))
_sym_db.RegisterMessage(ChatData)



_CONVERSATION = _descriptor.ServiceDescriptor(
  name='Conversation',
  full_name='Conversation',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=88,
  serialized_end=138,
  methods=[
  _descriptor.MethodDescriptor(
    name='makeChat',
    full_name='Conversation.makeChat',
    index=0,
    containing_service=None,
    input_type=_CHATDATA,
    output_type=_CHATDATA,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_CONVERSATION)

DESCRIPTOR.services_by_name['Conversation'] = _CONVERSATION

# @@protoc_insertion_point(module_scope)
