# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import conversation_pb2 as conversation__pb2


class ConversationStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.makeChat = channel.unary_unary(
        '/Conversation/makeChat',
        request_serializer=conversation__pb2.ChatData.SerializeToString,
        response_deserializer=conversation__pb2.ChatData.FromString,
        )


class ConversationServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def makeChat(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ConversationServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'makeChat': grpc.unary_unary_rpc_method_handler(
          servicer.makeChat,
          request_deserializer=conversation__pb2.ChatData.FromString,
          response_serializer=conversation__pb2.ChatData.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Conversation', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
